services:
  frankenphp:
    build:
      context: .
      dockerfile: .docker/frankenphp.Dockerfile
    container_name: pccd-frankenphp
    ports:
      - ${HTTP_PORT:-8092}:80
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pccd}
      MYSQL_USER: ${MYSQL_USER:-pccd}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOSTNAME: mysql
      WEB_ADMIN_PASSWORD: ${WEB_ADMIN_PASSWORD}
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - "./:/srv/app"

  mysql:
    image: mariadb:11.8.6-noble
    container_name: pccd-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pccd}
      MYSQL_USER: ${MYSQL_USER:-pccd}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 60
    restart: unless-stopped
    volumes:
      - "./.docker/mysql:/etc/mysql/conf.d"
      - "./install/db:/docker-entrypoint-initdb.d"
      - "pccd-mysql-data:/var/lib/mysql"

volumes:
  pccd-mysql-data:

networks:
  default:
    name: pccd-net
